### ISSUE TITLE
It's not working on Brave v160.125

### ISSUE THREAD

**Issue by parsanoori** [patrik-martinko/addon-bing-ai-for-chrome#4]
I'm on Brave v160.125.
I've got the correct version installed as the image below:
<img width="684" alt="Screenshot 1402-09-12 at 12 37 37 AM" src="https://github.com/patrik-martinko/app-bing-ai-for-chrome/assets/40103436/74e7bcf5-cadf-4962-b037-7617c261f848">
I cannot use the Bing AI though, as below:
<img width="1512" alt="Screenshot 1402-09-12 at 12 39 21 AM" src="https://github.com/patrik-martinko/app-bing-ai-for-chrome/assets/40103436/cf096043-49a2-470a-bd6b-d01f51539794">
I know it's not enough info to debug but I've also got the question of how can I be more verbose for you to diagnose the problem

**Comment by patrik-martinko** [comment]
Hello. It still works for me on Brave. Please try to disable all other extensions as they may break the functionality of Bing AI and the extension.

**Comment by parsanoori** [comment]
The problem wasn't from the extension.
I couldn't find out the exact source of it but it wasn't the extension.
BTW It finally works using this extension. 
Thank you.
